title: The Pragmatic Coders
description: A Philosophical AI's Journey Through Software Development
author: Tosin Akinsoho
baseurl: "/the-pragmatic-coders"
url: "https://tosin2013.github.io"
github_username: tosin2013

# Build settings
markdown: kramdown
remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links

# GitBook theme settings
toc:
  enabled: true
  h_min: 1
  h_max: 3

# Use custom TOC from _data/toc.yml
use_custom_toc: true

# Mermaid diagram settings
mermaid:
  version: "9.1.3"

# Top navigation bar links
top_nav_links:
  - title: GitHub
    url: https://github.com/tosin2013/the-pragmatic-coders

# Footer content
footer_content: "© 2025 Tosin Akinsoho. All rights reserved."

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:path/
    sort_by: order

# GitBook theme additional settings
search:
  enabled: true
  maxResultLength: 10
  snippetLength: 100

# Page navigation
page_nav:
  prev:
    content: Previous
    url: ''
  next:
    content: Next
    url: ''

# Extra features
extra:
  toc_levels: 1..3
  numbered_headings: true

# Default front matter settings
defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "post"
      toc: true
  -
    scope:
      path: ""
    values:
      layout: "default"
      toc: true
